# Site settings
title: Ron Martinez Is Doing Something
email: ramartin.net@gmail.com
description: >
  Ron Martinez is doing something that usually involves web development and occassionally other things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ramartin.net" # the base hostname & protocol for your site
twitter_username: icylace
github_username:  icylace

# Build settings
markdown: kramdown
