<?php
/**
 * @file
 * Birthday presents for Carrie Joyce.
 */


include_once dirname(__FILE__) . '/ramartinhbc.imagecache.inc';


// ------------------------------------------------------- Hook Implementations


/**
 * Implementation of hook_menu().
 */
function ramartinhbc_menu() {
  $items = array();

  $items['happy-birthday-carrie'] = array(
    'title'             => 'Poetry',
    'page callback'     => '_ramartinhbc_page',
    'access arguments'  => array('access content'),
    'type'              => MENU_CALLBACK,
  );

  $items['happy-birthday-carrie/%'] = array(
    'title'             => 'Poetry',
    'page callback'     => '_ramartinhbc_page',
    'page arguments'    => array(1),
    'access arguments'  => array('access content'),
    'type'              => MENU_CALLBACK,
  );

  return $items;
}


// ----------------------------------------------------------------------------


/**
 * Override or insert variables into the page templates.
 *
 * @param $vars
 *   An array of variables to pass to the theme template.
 */
function ramartinhbc_preprocess_page(&$vars) {
  /* *
  if (arg(1) === 'happy-birthday-carrie') {
    $vars['head_title'] = 'HAPPY BIRTHDAY CARRIE !!!';
  }
  /* */
}


// ----------------------------------------------------------------------------


/**
 * Implementation of hook_theme_registry_alter().
 */
function ramartinhbc_theme_registry_alter(&$theme_registry) {
  /**
   * http://data.agaric.com/node/2719
   */

  $templates_path = drupal_get_path('module', 'ramartinhbc') .'/templates';

  // Add the module templates path on top in the array of paths
  // for the theme hook page.
  array_unshift($theme_registry['page']['theme paths'], $templates_path);
}


// ---------------------------------------------------------- Private Functions
// ----------------------------------------------------------------------------


function _ramartinhbc_page($page = '') {
  $module_path = drupal_get_path('module', 'ramartinhbc');
  drupal_add_css($module_path . '/styles/ramartinhbc.css');

  $markups = array();

  switch ($page) {
    case '':
      $markups = array(
        '<ul id="gifts">',
          '<li>' . l('2009', 'happy-birthday-carrie/2009') . '</li>',
          '<li>' . l('2010', 'happy-birthday-carrie/2010') . '</li>',
        '</ul>',
      );
      break;

    case '2009':
      $markups = array(
        '<pre>',
        '',
        '',
        '',
        '',
        '',
        '',
        '                                                                                                                               _  _     ___      ___     ___  __   __           ___     ___     ___    _____   _  _     ___     ___   __   __           ___     ___     ___     ___     ___     ___              _      _      _                          ',
        '                o O O                                                                                                         | || |   /   \    | _ \   | _ \ \ \ / /          | _ )   |_ _|   | _ \  |_   _| | || |   |   \   /   \  \ \ / /          / __|   /   \   | _ \   | _ \   |_ _|   | __|            | |    | |    | |                         ',
        '               o                                                                                                              | __ |   | - |    |  _/   |  _/  \ V /           | _ \    | |    |   /    | |   | __ |   | |) |  | - |   \ V /          | (__    | - |   |   /   |   /    | |    | _|             |_|    |_|    |_|                         ',
        '              TS__[O]                                                                                                         |_||_|   |_|_|   _|_|_   _|_|_   _|_|_           |___/   |___|   |_|_\   _|_|_  |_||_|   |___/   |_|_|   _|_|_           \___|   |_|_|   |_|_\   |_|_\   |___|   |___|           _(_)_  _(_)_  _(_)_                        ',
        '             {======| |"""""| |"""""| |"""""| |"""""| |"""""| |"""""| |"""""| |"""""| |"""""| |"""""| |"""""| |"""""| |"""""| |"""""| |"""""| | """ | | """ | | """ | |"""""| |"""""| |"""""| |"""""| | """ | |"""""| |"""""| |"""""| | """ | |"""""| |"""""| |"""""| |"""""| |"""""| |"""""| |"""""| |"""""| | """ || """ || """ |                       ',
        '            ./o--000\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-\'"`-0-0-"`-0-0-"`-0-0-\'                        ',
        '</pre>',
      );
      break;

    case '2010':
      $images = array(
        'hbc-2010-1.jpg',
        'hbc-2010-2.jpg',
        'hbc-2010-3.jpg',
        'hbc-2010-4.jpg',
        'hbc-2010-5.jpg',
        'hbc-2010-6.jpg',
        'hbc-2010-7.jpg',
      );

      $markups = array('<ul id="hbc-2010">');

      foreach ($images as $image) {
        $markups[] = '<li>' . l(theme('imagecache', 'ramartinhbc_2010_gallery_image', $module_path . '/images/hbc-2010/' . $image, '', '', NULL, FALSE), $module_path . '/images/hbc-2010/' . $image, array('html' => TRUE)) . '</li>';
      }

      $markups[] = '</ul>';

      break;

    default:
      drupal_goto('happy-birthday-carrie');
  }

  drupal_set_title('HAPPY BIRTHDAY CARRIE !!!');

  return implode(PHP_EOL, $markups);
}
