<?php
/**
 * @file
 */


// ----------------------------------------------------------------------------


/**
 * Implements hook_menu().
 */
function ramartinrr_menu() {
  $items = array();

  $items['rr'] = array(
    'title'             => 'Raising Resilience',
    'page callback'     => '_ramartinrr_page',
    'access arguments'  => array('access content'),
    'type'              => MENU_CALLBACK,
  );

  return $items;
}


// ----------------------------------------------------------------------------


/**
 * Implements hook_theme().
 */
function ramartinrr_theme($existing, $type, $theme, $path) {
  return array(
    'block__rr' => array('path' => $path . '/templates', 'template' => 'block--rr'),
    'html__rr'  => array('path' => $path . '/templates', 'template' => 'html--rr'),
    'page__rr'  => array('path' => $path . '/templates', 'template' => 'page--rr'),
  );
}


// ----------------------------------------------------------------------------


function _ramartinrr_page() {
  return '';
}
